pipeline {
    agent any

    tools {
        maven "maven-3.9"
        jdk "jdk-17"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Ashutosh6411/playwright-automation.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "mvn clean install -DskipTests"
            }
        }

        stage('Run Tests') {
            steps {
                sh "mvn test"
            }
        }

        stage('Archive Reports') {
            steps {
                junit 'target/surefire-reports/*.xml'
                archiveArtifacts artifacts: 'target/**/*', fingerprint: true
            }
        }
    }

    post {
        always {
            echo "Build finished!"
        }
    }
}
